### ISSUE TITLE
Division stratégique 

### ISSUE THREAD

**Issue by jadjay** [ethibox/ethibox#44]
Bonjour,

On a déjà dû te le faire remarquer... Mais pourquoi ne joint tu pas tes efforts à des projets existants ?

Courage,

**Comment by pierreozoux** [comment]
@ston3o il faut qu'on discute :) (I created http://libre.sh )
https://riot.allmende.io/#/room/#libre.sh:matrix.allmende.io

**Comment by unteem** [comment]
wow en effet il faut que l'on discute :), je fais tourner indie.host (j'ai repris la relève de @pierreozoux ), je suis presque triste de découvrir ethibox que maintenant en fait et de voir que tu es aussi CHATONS. Très très beau travail @ston3o :+1: Je vais tester tout ca sur notre cluster au plus vite :)

**Comment by almereyda** [comment]
Est-ce que cette conversation a continue dans un autre espace?

**Comment by johackim** [comment]
Ce repository n'est plus maintenu, je ferme les issues.

**Comment by pierreozoux** [comment]
@johackim si tu es encore intéressé,  passe nous voir sur 
Https://chat.lescommuns.org on est en train de monter un grosmatou :)
