### ISSUE TITLE
Stuck at Start

### ISSUE THREAD

**Issue by javierox** [ethibox/ethibox#78]
## Steps to reproduce the problem

  1. docker run --name ethibox -p 4444:4444 ethibox/ethibox
Unable to find image 'ethibox/ethibox:latest' locally
latest: Pulling from ethibox/ethibox
a073c86ecf9e: Pull complete 
db7179d8c6cd: Pull complete 
66b9cfaecc8c: Pull complete 
b89fe290bec9: Pull complete 
84e24c694e57: Pull complete 
570ac2720006: Pull complete 
fa9ed88fc44d: Pull complete 
Digest: sha256:d0b66a83619d6ba295c9604b1bdded9e560087f086afc27a3e59d629e23dd4b5
Status: Downloaded newer image for ethibox/ethibox:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"": unknown.
ERRO[0014] error waiting for container: context canceled 

## Specifications

  - Version: Docker Version 
    docker --version
    Docker version 18.06.1-ce, build e68fc7a
  - Platform:
     lsb_release -a
     No LSB modules are available.
    Distributor ID:	Ubuntu
     Description:	Ubuntu 18.04.2 LTS
    Release:	18.04
     Codename:	bionic

4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

**Comment by ston3o** [comment]
Hello @javierox,

Thanks for your issue.

This error is not due to Ethibox. Maybe try to execute this command : `sudo systemctl restart docker`

Source: https://github.com/moby/moby/issues/29640#issuecomment-273617532
