### ISSUE TITLE
installation stops

### ISSUE THREAD

**Issue by johnnyhh123** [ethibox/ethibox#79]
1.) I enter:
docker run --name ethibox -p 4444:4444 ethibox/ethibox

Result:
Digest: sha256:d0b66a83619d6ba295c9604b1bdded9e560087f086afc27a3e59d629e23dd4b5
Status: Downloaded newer image for ethibox/ethibox:latest
Stop

2.) I enter:
docker run --name ethibox -p 4444:4444 ethibox/ethibox.fr

Result:
[HPM] Proxy created: /api  ->  https://api.ethibox.fr/function/api
Stops

Ubuntu 18.04
Docker version 18.06.1-ce

am I doing something wrong? if yes, what?
Thanks

**Comment by ston3o** [comment]
Hello @johnnyhh123, 

Thanks for your issue.

docker image `ethibox/ethibox.fr` is not related to this project.

And, when you run `docker run --name ethibox -p 4444:4444 ethibox/ethibox` there is no other logs and no display on http://localhost:4444 ?

**Comment by johnnyhh123** [comment]
hey @ ston3o thanks for the quick response.

it looked like it was stopping. but everything works as you said. Thank you
