### ISSUE TITLE
Self-host ethibox : custom domain

### ISSUE THREAD

**Issue by timconsidine** [ethibox/ethibox#96]
Installed ethibox and running using docker on a self-host VPS.
Add an app and add a custom domain
UI says to set DNS to 127.0.0.1. 
Really ? How will this ever work when set on a registrar DNS ?

**Comment by johackim** [comment]
Hello @timconsidine,

You can setup your default root domain on `/admin`.

![Admin Panel](https://user-images.githubusercontent.com/5039608/135487442-c0624ee6-5005-4a28-9969-83f2292be68d.png)

**Comment by timconsidine** [comment]
Thanks.
I didn't see any mention of /admin in the docs

**Comment by johackim** [comment]
Thanks for the feedback, I moved the hidden `/admin` path to the `/settings` tab.

**Comment by rasos** [comment]
How can I become an admin? Use the JWT token in the password field? Also in the URL like http://localhost:3000?jwt=mys3cr3t did not work for me.  I do not see an additional admin page in the settings with the first user.
