### ISSUE TITLE
ethibox latest : npm updates

### ISSUE THREAD

**Issue by timconsidine** [ethibox/ethibox#98]
I am getting the following when running the recommended docker run command
```
Update available 2.29.1 -> 3.1.1                       │
  Run the following to update                            │
    npm i --save-dev prisma                              │
    npm i @prisma/client     
```
I can do this with `docker exec -it <container> /bin/bash`
But is it possible to get this done in the docker file ?

**Comment by johackim** [comment]
This message is generated by prisma. It will appear each time there is a new prisma update.

I can only hide this message if needed, but I can't update prisma each time there is a new version.

**Comment by timconsidine** [comment]
OK no problem, understood
No need to change anything then.
It seems to run ok otherwise

**Comment by timconsidine** [comment]
I'm finding that installed apps are re-installing themselves.
Is there some setting which I am missing ?

**Comment by johackim** [comment]
@timconsidine Can you post a new issue ? Thanks :)
